# This is a basic workflow to help you get started with Actions

name: CD_App1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - 'main'
    paths: 'app1/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_dev_app1:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3

      - name: Deploy Dev App1
        run: echo Deploy App1 to Dev sha ${{ github.sha }}

  deploy_prod_app1:
    runs-on: ubuntu-latest
    environment: prod
    needs: deploy_dev_app1
    steps:
      - uses: actions/checkout@v3

      - name: Deploy Prod App1
        run: echo Deploy App1 to Prod sha ${{ github.sha }}
