# This is a basic workflow to help you get started with Actions

name: CI_CD_App1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: echo Build sha ${{ github.sha }}

  deploy_dev:
    runs-on: ubuntu-latest
    needs: build
    environment: dev
    steps:
      - uses: actions/checkout@v3

      - name: Deploy Dev
        run: echo Deploy to Dev sha ${{ github.sha }}

  deploy_prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: deploy_dev
    steps:
      - uses: actions/checkout@v3

      - name: Deploy Prod
        run: Deploy to Prod sha ${{ github.sha }}
